#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/dlspwalls
# Started On        - Sun 15 Oct 20:48:22 BST 2017
# Last Change       - Tue  3 Apr 12:51:06 BST 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2018-04-03"

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            DLSPWALLS ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            Download a collection of steampunk wallpapers.

		SYNTAX:     dlspwalls [OPTS]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --quiet|-q              - Runs in quiet mode. Errors still output.
		            --debug|-D              - Enables the built-in bash debugging.

		NOTE:       Files will be download to the current directory, as JPGs.

		SITE:       https://wallpapercave.com
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"
			exit 0 ;;
		--quiet|-q)
			BEQUIET="true" ;;
		--debug|-D)
			DEBUGME="true" ;;
		*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
	esac

	shift
done

[ -x /usr/bin/wget ] || ERR "$LINENO" "Dependency '/usr/bin/wget' not met."

read -a WGET_VER_LINE <<< "$(/usr/bin/wget --version)"
WGET_VERSION=0${WGET_VER_LINE[2]//[!0-9]}
if [ $WGET_VERSION -ge 01192 -a $WGET_VERSION -lt 01194 ]; then
	NOWARC="--no-warc-compression"
fi

[ "$BEQUIET" == "true" ] && exec 1> /dev/null
[ "$DEBUGME" == "true" ] && set -x
SRC1=steampunk-wallpaper
SRC2=steampunk-wallpaper-1920x1080
SRC3=steampunk-desktop-wallpaper
SRC4=steampunk-wallpapers
SRC5=steampunk-background
SRC6=steampunk-desktop-background
SRC7=steampunk-wallpaper-hd
SRC8=steampunk-backgrounds

URL="https://wallpapercave.com/download/steampunk-wallpaper"
HTML=`/usr/bin/wget -q $NOWARC "${URL%/down*}/${SRC2}" -O -`
printf "%s\n" "URL: ${URL}"
printf "%s\n" "HTML: ${URL%/down*}/${SRC2}"

GETID=()
while read -a Y; do
	for FIELD in ${Y[@]/src=\"\/wp}; {
		[ "$FIELD" == "$OLD" ] && continue
		if [[ "$FIELD" == /* ]]; then
			if [[ "$FIELD" =~ [0-9A-Za-z]+.jpg ]]; then
				GETID+=("${FIELD%.jpg\"}")
			fi
		else
			continue
		fi

		OLD="$FIELD"
	}
done <<< "$HTML"

declare -i N=0
for ID in ${GETID[@]//\/}; {
	N+=1

	printf "%s\n" "DOWNLOADING: ${SRC2}-${ID}.jpg"
	printf -v FNAME "./${SRC2}-%0.2d.jpg" "${N}"
	printf "%s\n" "URL: ${URL}-1920x1080-${ID}"
	/usr/bin/wget -qc $NOWARC "${URL}-1920x1080-${ID}" -O "$FNAME"
}

# vim: ft=sh noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
