#!/bin/bash

x=$(echo -e "lock\nsuspend\nhibernate\nreboot\nshutdown\nlogout" | dmenu -i -p "Choose?")

case "$x" in
    lock)
        blurlock && disown
        ;;
    logout)
        i3-msg exit && disown
        ;;
    suspend)
		SUDO_ASKPASS=~/.scripts/dpass sudo -A bash -c 'blurlock; systtemctl suspend'
        ;;
    hibernate)
		SUDO_ASKPASS=~/.scripts/dpass sudo -A bash -c 'blurlock; systemcts hibernate'
        ;;
    reboot)
		SUDO_ASKPASS=~/.scripts/dpass sudo -A reboot
        ;;
    shutdown)
		SUDO_ASKPASS=~/.scripts/dpass sudo -A systemctl poweroff
        ;;
esac
